services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.6
    ports:
    - 8080:8080
    - 50051:50051
    restart: on-failure:0
    env_file: ".env"
    volumes:
      - ~/google_credentials.json:/etc/weaviate/google_credentials.json:ro
    environment:
      USE_GOOGLE_AUTH: 'true'
      GOOGLE_APPLICATION_CREDENTIALS: '/etc/weaviate/google_credentials.json'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'multi2vec-google'
      ENABLE_MODULES: 'multi2vec-google'
      CLUSTER_HOSTNAME: 'node1'
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}